# Frontend CI workflow for ERP Final
# Tests Node.js frontend code with fail-safe for missing frontend directory

name: Frontend CI

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Check if frontend directory exists
      id: check-frontend
      run: |
        if [ -d "frontend" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Frontend directory found"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "Frontend directory not found - skipping frontend CI"
        fi
        
    - name: Set up Node.js
      if: steps.check-frontend.outputs.exists == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      if: steps.check-frontend.outputs.exists == 'true'
      working-directory: ./frontend
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        elif [ -f package.json ]; then
          npm install
        else
          echo "No package.json found - skipping dependency installation"
          exit 0
        fi
        
    - name: Run linting
      if: steps.check-frontend.outputs.exists == 'true'
      working-directory: ./frontend
      run: |
        if npm run | grep -q "lint"; then
          echo "Running lint script"
          npm run lint
        else
          echo "No lint script found - skipping linting"
        fi
        
    - name: Build frontend
      if: steps.check-frontend.outputs.exists == 'true'
      working-directory: ./frontend
      run: |
        if npm run | grep -q "build"; then
          echo "Running build script"
          npm run build
        else
          echo "No build script found - skipping build"
        fi
        
    - name: Frontend CI completed
      run: |
        if [ "${{ steps.check-frontend.outputs.exists }}" == "true" ]; then
          echo "Frontend CI completed successfully"
        else
          echo "Frontend CI skipped - no frontend directory found"
        fi